### ISSUE TITLE
DockerExists doesn't work properly

### ISSUE THREAD

**Issue by blaggacao** [Docker-nano/nano#1]
Hi,
Line : https://github.com/Docker-nano/nano/blob/master/nano#L102

Does not behave as expected probably due to changes in the docker client.

```
$ docker -v
Docker version 1.9.1-rc1, build aba5981
```

**Comment by Bilge** [comment]
You're probably right, I'm still on v1.4. I didn't realise anyone was interested in this project! Maybe I'll fix it.

**Comment by Bilge** [comment]
This is now fixed in [version 1.1](https://github.com/Docker-nano/nano/commit/810ef4510118febd41c5ff3d00cd0b7322b86cc8).

**Comment by blaggacao** [comment]
thx, to me, it is a very usefull project as it structures the whole buildroot process according to the tools I know...
